on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Store hello
        uses: ./ # Uses an action in the root directory
        with:
          command: gcc -v > output.txt
      - name: Read hello
        uses: ./
        with:
          command: cat output.txt
      - name: Check for self checkout, e.g. entrypoint.sh
        uses: ./
        with:
          command: ls     
